# Generated by Django 4.2.2 on 2024-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treaty',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер договора'),
        ),
    ]
