# Generated by Django 4.2.2 on 2024-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_treaty_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treaty',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер договора'),
        ),
    ]
