# Generated by Django 4.2.2 on 2024-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_treaty_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='Дата за которую подают показание'),
        ),
    ]
