# Generated by Django 4.2.2 on 2024-04-14 16:06

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_record_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='month',
            field=month.models.MonthField(blank=True, null=True),
        ),
    ]
